import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });
import { IoMdHome } from "react-icons/io";
import BackButton from "./Components/BackButton";
import TopBar from "./Components/TopBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#DDE4E650]">
      <body>
        <Providers>
          <TopBar />
          <div className="p-5">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
