import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import TopBar from "./Components/TopBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#DDE4E650]">
      <body>
        <Providers>
          <div>
            <TopBar />
            <div className="p-5">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
